Hw02 unpack string
shimmy8/hw-otus pull request #2
Opened 2023-06-13 14:31 UTC by shimmy8

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-13 18:02 UTC, vladislavmass requested changes
Отличное начало. Радует что используется strings.Builder. Также правильно подобраны все имена переменных. В коде есть ошибки, поэтому работу принять не могу. Также рекомендую разбить код на блоки с помощью пустых строк, это улучшить и так хорошую читаемость кода.

2023-06-13 18:02 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +		} else if prevStr > "9" { // current rune and prevStr are not numbers
А что будет если я захочу распаковать строку вида !!2abcd? Строка корректная, но восклицательный знак находится в таблице  ASCII до 0 и следовательно на него это условие не сработает.

2023-06-13 18:02 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +	if prevStr > "9" { // write last symbol if not a number
Таже самая проблема что и выше.

2023-06-14 06:36 UTC, shimmy8 commented on hw02_unpack_string/unpack.go
> +		} else if prevStr > "9" { // current rune and prevStr are not numbers
Поправил и добавил тест

2023-06-14 09:46 UTC, vladislavmass approved these changes
Хорошая работа. Ошибки удачно исправлены. Работа принята 10/10.

2023-06-14 09:46 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	var prevStr string
Хранить символ как строку достаточно накладное занятие. Подумайте о том, что бы работать с рунами. При таком подходе вам конвертация к  строке будет нужна только в одном месте.

2023-06-14 10:43 UTC, merged