hw04 done
shimmy8/hw-otus pull request #4
Opened 2023-07-10 08:46 UTC by shimmy8

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-11 18:17 UTC, hungry-honeybadger requested changes
Отличное начала. Радует правильная реализация двусвязного списка и большое количества тестов. В Коде есть ряд багов мешающих принять работу

2023-07-11 18:17 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	FirstItem *ListItem
С какой целью первый и последний элемент делаются экспортируемыми?

2023-07-11 18:17 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		cache.queue.PushFront(cachedElem)
Пуш фронт добавляет текущий элемент в начало очереди, но он его не удаляет из очереди. Тут должна использоваться операция `MoveToFront`

2023-07-11 18:17 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
Из списка элемент удаляется, но в мапе он остается и получается что размер мапы вечно растет без очистки.

2023-07-11 18:17 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +func (cache lruCache) Set(key Key, i interface{}) bool {
Функции `Set` и `Get` изменяют объект `lruCache`, поэтому лучше в сигнатуре функции писать `(cache *lruCache)`.

2023-07-12 05:44 UTC, shimmy8 commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
> Из списка элемент удаляется, но в мапе он остается и получается что размер мапы вечно растет без очистки.

Что-то я не могу придумать как мне из мапы удалить по значению за О(1). Можно подсказку? =)

2023-07-12 05:46 UTC, shimmy8 commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
Думал добавить тип `type CacheItem struct {
	ListItem
	key Key
}`

Но list вернет ведь *ListItem

2023-07-12 06:10 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
Внутри `ListItem` есть `Value`. Предлагаю подумать о том, что бы в нем хранить и значение и ключ.

2023-07-12 07:27 UTC, shimmy8 commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
Спасибо) поправил

2023-07-12 08:35 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if cache.capacity == cache.queue.Len() {
Жду работу на проверку через Отус)

2023-07-13 05:21 UTC, vladislavmass requested changes
Хорошие правки. Теперь кэш написан правильно. Но остался один момент по реализации списка.

2023-07-13 05:21 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	cache.items = make(map[Key]*ListItem)
Тут можно было тоже использовать `capacity` что бы избежать лишних аллокаций

2023-07-13 05:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	listItem := ListItem{Value: v}
Более красивый вариант в данном случае это `listItem := &ListItem{Value: v}`. Это позволит сразу создать ссылку и потом ее присваивать, за место кучи операции взятия адреса

2023-07-13 05:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	listItem := ListItem{Value: v}
Более красивый вариант в данном случае это `listItem := &ListItem{Value: v}`. Это позволит сразу создать ссылку и потом ее присваивать, за место кучи операции взятия адреса

2023-07-13 05:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (lst *list) MoveToFront(i *ListItem) {
Чему по итогу будет равен `lastItem` если мы вызовем этот метод и передадим ему последний элемент в списке?

2023-07-13 12:44 UTC, shimmy8 commented on hw04_lru_cache/list.go
> +func (lst *list) MoveToFront(i *ListItem) {
Исправил и добавил тест, спасибо!

2023-07-13 13:17 UTC, vladislavmass approved these changes
Отлично. Работа принята. 10/10

2023-07-13 13:17 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (lst list) Len() int {
В go принято использовать одну и туже нотацию, поэтому тут лучше использовать `func (lst *list) Len() int`

2023-07-15 07:21 UTC, merged