hw07 complete
shimmy8/hw-otus pull request #7
Opened 2023-08-17 12:22 UTC by shimmy8

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-18 04:41 UTC, vladislavmass requested changes
Классное начало. Порадовал свой собственный прогресс бар. Очень мало кто его делает сам. Программа очень медленно работает поэтому принять не могу

2023-08-18 04:41 UTC, hungry-honeybadger commented on hw07_file_copying/progress.go
> +func copyNWithProgress(dst io.Writer, src io.Reader, nTotal int64) (int64, error) {
Функцию `copyNWithProgress` лучше перенести в файл `copy.go`. Все таки она относится к функционалу копирования я не прогресс бара.

2023-08-18 04:41 UTC, hungry-honeybadger commented on hw07_file_copying/progress.go
> +func (pb *ProgressBar) New(total int64) {
Имя функции `New` говорит о том, что это скорее метод-конструктор. Предлагаю сделать из нее этот самый конструктор

2023-08-18 04:41 UTC, vladislavmass commented on hw07_file_copying/progress.go
> +	var chunkSize int64 = 16
Использовать столь малый размер чанков плохая идея. Для малых файлов это будет почти незаметно, а вот на больших файлах будет гигантская просадка скорости копирования Тут больше бы подошла некая формула. например `nTotal/100`

2023-08-18 05:11 UTC, shimmy8 commented
> Классное начало. Порадовал свой собственный прогресс бар. Очень мало кто его делает сам. Программа очень медленно работает поэтому принять не могу

А какой критерий скорости работы, тесты должны за n проходить? Хочется знать к чему стремиться)

2023-08-18 05:39 UTC, vladislavmass commented
> > Классное начало. Порадовал свой собственный прогресс бар. Очень мало кто его делает сам. Программа очень медленно работает поэтому принять не могу
> 
> А какой критерий скорости работы, тесты должны за n проходить? Хочется знать к чему стремиться)

Критериев по скорости в этом задание нет. Просто именно такая реализация превращает 2 минутное копирование файла в 50 гб в копирование когда за 5 минут копируется 1%

2023-08-21 06:13 UTC, vladislavmass approved these changes
Хорошая работа. 10/10. Принято

2023-08-21 06:29 UTC, merged